# Generated by Django 4.0.4 on 2022-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Number', models.CharField(max_length=12)),
                ('select', models.CharField(max_length=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
